lib/components/Drawer/Drawer.stories.tsx, lib/components/Drawer/index.tsx, lib/components/Drawer/styles.scss, lib/components/Header/Header.stories.tsx, lib/components/Header/parts/HeaderNavbarLink.tsx, lib/components/Header/styles.scss, lib/components/ProfileNav/index.tsx, lib/components/ProfileNav/styles.scss, lib/components/Text/Text.stories.tsx, lib/components/Text/index.tsx, lib/components/Text/styles.scss, lib/components/Text/types.ts
Adicionando novo componente `Drawer` para usar no menu mobile
=> feat: add Drawer component

lib/components/NavbarVertical/NavbarVertical.stories.tsx, lib/components/NavbarVertical/index.tsx, lib/components/NavbarVertical/styles.scss
Novo componente de navegação `NavbarVertical`
=> feat: new component navbar vertical to mobile version

lib/components/Drawer/styles.scss, lib/components/Header/styles.scss, lib/components/NotificationsBar/styles.scss, package.json
Style fixes in Header component
=> fix: header component styles

lib/main.ts
- adição do export do componente footer
=> chore: add footer export

lib/components/Text/styles.scss
- Changed the breakpoint for variantDesktop from `aboveSmall`(320px) to `aboveLarge`(1024px)."
=> refactor: (text component) changing breakpoint for desktop variant

lib/components/Footer/index.tsx, lib/components/Footer/styles.scss
Neste PR estou adicionando o container faltante no footer para o conteúdo ficar alinhado com o header, tanto para área logada, quanto para área aberta.
**Sem o container (atual):**
**Com o container:**
=> fix: add footer container

lib/core/tokens/typography.json
Removed unused font family name
=> Remove variable font name

lib/components/Button/styles.scss, lib/components/Header/styles.scss, lib/components/Text/styles.scss, lib/core/styles/GlobalStyles.scss, lib/core/tokens/typography.json
Setting fonts tokens names to more descriptive names.
=> Renaming font family variables

lib/components/Footer/styles.scss
Neste PR estou alterando a cor do divider do footer, estávamos usando o token `color-neutral-30` e o correto de acordo com o figma seria `color-neutral-20.`
=> fix: change divider color

lib/components/Button/button.stories.tsx, lib/components/Button/index.tsx, lib/components/Button/styles.scss, lib/components/form/PasswordField/styles.scss, lib/core/tokens/colors.json
- add prop round para criar variação de botão redondo:
- atualização das cores de hover e active do botão.
- add font family no botão do input de senha
=> feat: add round button and button style adjustments

lib/components/form/CheckboxField/CheckboxField.stories.tsx, lib/components/form/Field/ErrorMessage.tsx, lib/components/form/Field/Label.tsx, lib/components/form/InputField/InputField.stories.tsx, lib/components/form/PasswordField/PasswordField.stories.tsx, lib/components/form/SelectField/SelectField.stories.tsx, lib/components/form/TokenField/TokenField.stories.tsx
- adicionar null nos return vazios dos componentes;
- add altura e background nas docs de componentes de form
=> Ajuste de return e docs

lib/components/Footer/data.tsx, lib/components/Footer/index.tsx, lib/components/Header/parts/HeaderHamburger.tsx, lib/components/Header/parts/HeaderLogo.tsx, lib/components/Header/parts/HeaderNavbarLink.tsx, lib/components/Header/parts/HeaderProfile.tsx, lib/components/IsMobile/index.tsx, lib/components/LazyImage/index.tsx, lib/components/NavbarVertical/index.tsx, lib/components/ProfileNav/index.tsx, lib/components/Text/index.tsx, lib/components/form/CheckboxField/index.tsx, lib/components/form/Datepicker/Calendar/hook.ts, lib/components/form/Datepicker/Calendar/index.tsx, lib/components/form/Datepicker/CalendarHeader/index.tsx, lib/components/form/Datepicker/PortalHolder/index.tsx, lib/components/form/Datepicker/Segment/hook.ts, lib/components/form/Datepicker/Segment/index.tsx, lib/components/form/Datepicker/hook.ts, lib/components/form/Datepicker/index.tsx, lib/components/form/Field/Label.tsx, lib/components/form/SelectField/index.tsx, lib/core/tokens/index.ts, lib/main.ts, tsconfig.json, vite.config.ts
Adicionando:
* Imports absolutos;
* Campo de texto do datepicker como type `tel` para forçar o teclado numérico.
=> Absolute imports + datepicker improvement

lib/components/form/SelectField/styles.scss
- removido padding que atrapalhava a mensagem de erro
=> Ajustes no componente select

lib/components/form/SelectField/SelectField.stories.tsx, lib/components/form/SelectField/hook.ts, lib/components/form/SelectField/index.tsx, lib/components/form/SelectField/styles.scss, lib/components/form/SelectField/types.ts
https://github.com/user-attachments/assets/8ae25b78-d26a-4fe6-a21d-5053b6d2de4d
=> feat: select autocomplete

lib/components/form/Radio/Field/RadioField.stories.tsx, lib/components/form/Radio/Field/index.tsx, lib/components/form/Radio/Field/styles.scss, lib/components/form/Radio/Group/RadioGroup.stories.tsx, lib/components/form/Radio/Group/index.tsx, lib/components/form/Radio/Group/styles.scss, lib/components/form/Radio/index.tsx, lib/components/form/Radio/types.ts, lib/main.ts
- Componente radio button 
- Grupo de radio buttons
=> Radio Button

lib/components/form/Field/TextArea.tsx, lib/components/form/Field/index.tsx, lib/components/form/Field/styles.scss, lib/components/form/TextareaField/TexareaField.stories.tsx, lib/components/form/TextareaField/index.tsx
=> feat: textarea

lib/components/form/Field/TextArea/hook.ts, lib/components/form/Field/TextArea/index.tsx, lib/components/form/Field/styles.scss, lib/components/form/TextareaField/TexareaField.stories.tsx
- remoção da customização do ícone de resize por possibilidade de bugs
=> fix: textarea

lib/components/form/SelectField/styles.scss
=> feat (select): add style to scrollbar

lib/components/Alert/Alert.stories.tsx, lib/components/Alert/index.tsx, lib/components/Alert/styles.scss, lib/main.ts
Este PR adiciona o componente de **Alert** a lib
=> feat: alert component

lib/components/form/SelectField/index.tsx
fix: change onClick to onPointerUp for option selection in SelectField
=> fix: change onClick to onPointerUp for option selection in SelectField

lib/components/Card/Card.stories.tsx, lib/components/Card/CardOffer.stories.tsx, lib/components/Card/Container/index.tsx, lib/components/Card/Emphasis/index.tsx, lib/components/Card/Image/index.tsx, lib/components/Card/Root/index.tsx, lib/components/Card/Tag/index.tsx, lib/components/Card/index.tsx, lib/components/Card/styles.scss, lib/components/Text/styles.scss, lib/components/icons/Icon.tsx, lib/components/icons/styles.scss
Este PR contempla o componente de Card genérico e aplicado em ofertas. 
**Genérico:**
**Ofertas:**
=> Card component

lib/components/Alert/Alert.stories.tsx, lib/components/Alert/index.tsx, lib/components/Alert/styles.scss
- add botão de fechar
- add onClick no action button
- add font family
=> Ajustes Alert

lib/components/Card/CardOffer.stories.tsx, lib/components/Card/Container/index.tsx, lib/components/Card/Root/index.tsx, lib/components/Card/styles.scss, lib/components/Skeleton/Skeleton.stories.ts, lib/components/Skeleton/index.tsx, lib/components/Skeleton/styles.scss, lib/main.ts
=> Skeleton Component

lib/components/Spinner/Spinner.stories.tsx, lib/components/Spinner/index.tsx, lib/components/Spinner/styles.scss, lib/main.ts
Neste PR estou adicionando o [componente Spinner](https://www.figma.com/design/mJ6TJpnbZZYLiGXYnpg84b/Aurora-DS?node-id=6785-23375&t=QhnUbojCSaDZenEW-0), ele aceita duas propriedades: `size` e `color`.
=> feat: add spinner

lib/components/Tabs/styles.scss
=> feat: add scroll for mobile on Tabs

lib/core/styles/mixins.scss, lib/core/tokens/layout.json
- FIX: max-width para o container.
- FEAT: Adiciona novas funções (below). Todos nossos projetos utilizam essas funções, sendo assim, só vamos conseguir padronizar e manter uma única fonte disponibilizando aqui tb.
Os arquivos scss (mixins e variables) já estão sendo expostos em tempo de build na raiz da pasta dist da lib
=> Mixins and Breakpoints

lib/components/NavbarVertical/index.tsx
Correção no status de `active` e `open` no component `NavbarVertical`
=> fix(NavbarVerfical): status active and open menu item

lib/components/Image/Image.stories.tsx, lib/components/Image/index.tsx
https://www.loom.com/share/f738234f196e4505bdedf08fbb11da47?sid=bdcb7537-6a41-4578-8b13-dba919f427e5
=> Image component

lib/components/ProgressBar/ProgressBar.stories.tsx, lib/components/ProgressBar/index.tsx, lib/components/ProgressBar/styles.scss
O componente ProgressBar não está completo no DS, porém, vamos utilizar ele dentro do novo fluxo unificação de Auth.
Consiste em duas versões:
- Modo porcentagem com barra de progresso
- Modo steps com indicação do current e total de steps
Aqui está o link DS para consultar - [ProgressBar](https://www.figma.com/design/mJ6TJpnbZZYLiGXYnpg84b/Aurora-DS?node-id=1582-4765&p=f&t=cUWSfwtmejhw5y0C-0)
https://github.com/user-attachments/assets/8d5693d0-c77c-498e-b411-c66bf4c9a1f7
=> Feat ✨: Progress Bar

lib/components/Alert/Alert.stories.tsx, lib/components/Alert/index.tsx, lib/components/Alert/styles.scss
Adicionando um novo status no componente de Alerta chamado "Timer", para os casos de envio de token por e-mail e SMS, onde o usuário precisará aguardar um tempo para solicitar um novo código.
Este novo status altera o ícone para o de um relógio e adiciona uma contagem regressiva abaixo, com um novo atributo de ação para quando o tempo se esgotar.
=> feat: new timer status in alert component

lib/components/Alert/index.tsx, lib/components/Alert/styles.scss
- Reiniciando a contagem regressiva ao clicar no botão
- Ajuste no alinhamento do ícone
=> update: restart countdown on button click

lib/components/Alert/styles.scss
Alterando a fonte do botão de link do componente de alerta para **Source Sans 3**.
=> feat: new font on alerts button

lib/components/Tabs/index.tsx
- Tipo renomado para facilitar identificação (de TabProps para TabItem)
- Expõe o type para consumo externo
- Adiciona o prefixo `au-` na classe principal do componente Tab.
Restante das alterações no arquivo foram feitas de foma automática pelo EsLint
=> FIX: Export Tab type

lib/components/Text/styles.scss
Esse PR altera o `line-height` dos Headings, component `<Text />`
https://aurora.consumidorpositivo.com.br/?path=/docs/components-text--docs
=> style(headings): change line-height value in pixel

lib/components/form/EmailField/EmailField.stories.tsx, lib/components/form/EmailField/hook.ts, lib/components/form/EmailField/index.tsx, lib/components/form/EmailField/styles.scss
Novo componente para campos de e-mail, com funcionalidade de autocomplete que sugere automaticamente os principais domínios de e-mail atuais após o usuário digitar o "@" durante o preenchimento.
https://github.com/user-attachments/assets/d8803bc3-e338-4076-b362-e09d327c3121
=> feat: EmailField component

lib/components/NavbarVertical/NavbarVertical.stories.tsx, lib/components/NavbarVertical/index.tsx, lib/components/NavbarVertical/styles.scss
- Alinhando a seta azul do dropdown à direita
- Adicionando bullets nos submenus do dropdown
- Nova área de alerta ao final do menu
=> update: NavbarVertical component

lib/assets/icons/default/id.svg, lib/components/icons/Icon.tsx, lib/components/icons/styles.scss, lib/docs/Icons.mdx
- Novo ícone de ID
- Nova opção de cor "success" para ícones verdes.
=> update: new icons & new color for icons

lib/main.ts
=> feat: add tag export

lib/components/Modal/Modal.stories.tsx, lib/components/Modal/index.tsx, lib/components/Modal/styles.scss, lib/components/form/SelectField/SelectField.stories.tsx, lib/components/form/SelectField/hook.ts, lib/components/form/SelectField/index.tsx, lib/components/form/SelectField/styles.scss, lib/components/form/SelectField/types.ts
Foi adicionado uma nova prop no SelectField: `FullScreenOptions`
=> Select com opções em tela cheia

lib/components/Footer/ac/FooterAC.stories.tsx, lib/components/Footer/cp/FooterCP.stories.tsx, lib/components/Footer/index.tsx, lib/components/Footer/styles.scss, lib/components/Footer/types.ts, lib/core/tokens/layout.json
- Acréscimo de novas páginas que não haviam sido adicionadas.
- Nova nomenclatura para títulos dos blocos de texto.
- Nova organização para blocos de textos.
- Orientações para baixar o App mudou de lugar.
- Padronização das nomenclaturas dos títulos com o CP.
- Orientações para baixar o App mudou de lugar.
- Nova organização para blocos de textos. 
- Social Midia de ambos os sites foi removida.
- Logo e Selos diminuiram um pouco de tamanho.
- Footer teve altura reduzida.
---
**Largura do container ajustada para 1200px**
=> refactor: Footer v2

lib/components/form/TokenField/styles.scss
Ajusta o input de token no navegador firefox
=> style: adjust input token on firefox

lib/components/form/TokenField/styles.scss
O ultimo ajuste funcionou no storybook mas não funcionou em prod nos apps (AC e CP).
=> style: adjust on firefox

lib/components/Footer/styles.scss, lib/components/Header/parts/HeaderNavbarLink.tsx, lib/components/Header/styles.scss, lib/components/NavbarVertical/styles.scss
Atualizações de estilo do Header e Footer.
[Link do QA](https://www.notion.so/consumidorpositivo/QA-AC-e-CP-Header-Footer-1fc1ec40f1b48048ad2cdf1012042857?source=copy_link)
=> [SCO-2340][QA] Header & Footer updates

lib/components/form/SelectField/hook.ts, lib/components/form/SelectField/index.tsx
Este PR ajusta o comportamento do select com full screen option, para que não aceite valores no campo de busca como valor válido.
=> fix: remove custom value in enable full screen option select

lib/components/Drawer/styles.scss, lib/components/Switch/Card/CardSwitch.stories.tsx, lib/components/Switch/Card/index.tsx, lib/components/Switch/Card/styles.scss, lib/components/Switch/Card/types.ts, lib/components/Switch/Pure/PureSwitch.stories.tsx, lib/components/Switch/Pure/index.tsx, lib/components/Switch/Pure/styles.scss, lib/components/Switch/Pure/types.ts, lib/main.ts
* add pure switch and card switch components
=> feat: ✨ add new switch component

lib/components/Card/Root/index.tsx
Adding custom classnames prop to Card component
=> feat: :sparkles: added custom classname to card

lib/components/Alert/Alert.stories.tsx, lib/components/Alert/index.tsx
Adding custom icon prop to alert component
=> feat: :sparkles: added custom icon prop to alert
